name: Release Pipeline

on:
  release:
    types: [created]

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & Push Docker Image
        run: |
          TAG=${{ github.event.release.tag_name }}
          docker build -t mydockerhubuser/myfastapi:$TAG .
          docker push mydockerhubuser/myfastapi:$TAG
